export { default as PhoneNumber } from './phone-number';
export { default as Otp } from './otp';
export { default as Voucher } from './voucher';
export { default as VoucherSuccess} from './voucher-success';
export { default as VoucherError } from './voucher-error';
export { default as VoucherExpired } from './voucher-expired';
export { default as Login } from './login';
export { default as NotSubscribe } from './not-subscribe';
export { default as Detail } from './detail';
export { default as SetResult } from './set-result';